# Nombre del flujo de trabajo
name: Deploy Next.js site to Pages with Bun

on:
  # Se ejecuta en cada push a la rama 'main'
  push:
    branches: ['main']

  # Permite ejecutar este flujo de trabajo manualmente
  workflow_dispatch:

# Configura los permisos del GITHUB_TOKEN para el despliegue
permissions:
  contents: read
  pages: write
  id-token: write

# Permite solo un despliegue concurrente
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  # Job de construcción (Build)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        # Esta es la acción oficial para instalar y configurar Bun
        uses: oven-sh/setup-bun@v1

      - name: Restaurar caché de Bun
        # Cache adaptado para Bun
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          # La clave de la caché ahora depende del archivo de bloqueo de Bun: bun.lockb
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Instalar dependencias con Bun
        # Usamos el comando de instalación de Bun
        # --frozen-lockfile es una buena práctica en CI para asegurar instalaciones consistentes
        run: bun install --frozen-lockfile

      - name: Configurar GitHub Pages
        # Este paso de Next.js sigue siendo necesario para configurar el basePath
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Construir la aplicación con Next.js
        # Ejecutamos el script de 'build' usando Bun
        run: bun run build

      - name: Subir el artefacto para el despliegue
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  # Job de despliegue (Deploy) - No cambia
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
